---
- name: Connect with SSH to Router
  hosts: router
  become: yes
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Add Description on Interface
      ios_config:
        lines:
          - description This is Loopback Interface
        parents: interface loopback0
        provider:
          username: rifandi
          password: rifandi
          port: 22
          auth_pass: cisco
          authorize: yes
        save_when: modified
