---
- name: Backup Device
  become: yes
  hosts: router
  gather_facts: no
  connection: network_cli
  tasks:

   - name: Backup  
     ios_command:
       commands: show run
       provider:
         username: rifandi
         password: rifandi
         port: 22
         auth_pass: cisco
         authorize: yes
     register: config

   - name: Save output to /etc/ansible/backupRouter
     copy:
       content: "{{config.stdout[0]}}"
       dest: "/etc/ansible/backupRouter/{{inventory_hostname}}-config.txt"