[router]

RTR1 ansible_host=10.0.1.1
RTR2 ansible_host=10.0.2.2
RTR3 ansible_host=10.0.3.3
RTR4 ansible_host=10.0.4.4
RTR5 ansible_host=10.0.5.5

[router:vars]

ansible_user=rifandi
ansible_password=rifandi
ansible_connection=local
ansible_network_os=ios
ansible_become=yes
ansible_become_password=yes
ansible_port=22

[router2]

RTR2 ansible_host=10.0.2.2

[router2:vars]

ansible_user=rifandi
ansible_password=rifandi
ansible_become=yes
ansible_become_method=enable
ansible_become_pass=cisco


