---

- name: Connect to Router
  hosts: router
  become: yes
  gather_facts: no
  connection: local

  tasks: 
    - name: Test Reachability to 8.8.8.8 using Ping
      ios_ping:
        dest: 8.8.8.8
        count: 50
        
        state: present
        provider:
          username: rifandi
          password: rifandi
          port: 22
          auth_pass: cisco
          authorize: yes

      register: hasil_ping

    - name: Ping output
      debug:
        var: hasil_ping['commands']

    - name: Round Trip Time Ping output
      debug:
        var: hasil_ping['rtt']

    - name: Packet that successfully received
      debug: 
        var: hasil_ping['packets_rx']

    - name: Packet that successfully received
      debug: 
        var: hasil_ping['packets_tx']






